name: nest-mpi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake>=3.19
  - openmpi=4.1.6
  - boost>=1.69
  - gsl>=1.11
  - libtool 
  - readline  
  - ncurses 
  - hdf5
  - cppcheck
  - doxygen
  - graphviz
  - mpi4py
  - cython
  - numpy<=1.26.4
  - pandas=2.2.2
  - scipy
  - matplotlib
  - h5py
  - black
  - pre-commit
  - isort
  - notebook
  - jupyterlab
  - csa
  - pydot
  - gcc
  - gxx
  - nose
  - junitparser
  - ipython
  - future
  - pytest
  - pytest-timeout
  - pytest-xdist
  - setuptools <= 65